# [spa_forever]

In [0]:
USE [master]
GO

In [0]:
/****** Object:  Database [spa_forever]    Script Date: 23/05/2023 23:11:22 ******/
CREATE DATABASE [spa_forever]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'spa_forever', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\spa_forever.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'spa_forever_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\spa_forever_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [spa_forever] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [spa_forever].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [spa_forever] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [spa_forever] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [spa_forever] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [spa_forever] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [spa_forever] SET ARITHABORT OFF 
GO
ALTER DATABASE [spa_forever] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [spa_forever] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [spa_forever] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [spa_forever] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [spa_forever] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [spa_forever] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [spa_forever] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [spa_forever] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [spa_forever] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [spa_forever] SET  DISABLE_BROKER 
GO
ALTER DATABASE [spa_forever] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [spa_forever] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [spa_forever] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [spa_forever] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [spa_forever] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [spa_forever] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [spa_forever] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [spa_forever] SET RECOVERY FULL 
GO
ALTER DATABASE [spa_forever] SET  MULTI_USER 
GO
ALTER DATABASE [spa_forever] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [spa_forever] SET DB_CHAINING OFF 
GO
ALTER DATABASE [spa_forever] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [spa_forever] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [spa_forever] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [spa_forever] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'spa_forever', N'ON'
GO
ALTER DATABASE [spa_forever] SET QUERY_STORE = ON
GO
ALTER DATABASE [spa_forever] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

# [dbo].[horarios]

In [0]:
USE [spa_forever]
GO

In [0]:
/****** Object:  Table [dbo].[horarios]    Script Date: 23/05/2023 23:11:22 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[horarios](
	[hor_id] [nchar](10) NULL,
	[hor_fecha] [datetime] NULL,
	[hor_hora] [time](7) NULL
) ON [PRIMARY]
GO

# [dbo].[permisos]

In [0]:
/****** Object:  Table [dbo].[permisos]    Script Date: 23/05/2023 23:11:22 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[permisos](
	[perm_id] [bit] NULL,
	[perm_desc] [nchar](100) NULL
) ON [PRIMARY]
GO

# [dbo].[productos]

In [0]:
/****** Object:  Table [dbo].[productos]    Script Date: 23/05/2023 23:11:22 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[productos](
	[prod_id] [nvarchar](50) NOT NULL,
	[prod_nom] [varchar](500) NOT NULL,
	[prod_precio] [nchar](10) NOT NULL,
	[prod_stock] [numeric](18, 0) NULL
) ON [PRIMARY]
GO

# [dbo].[servicios]

In [0]:
/****** Object:  Table [dbo].[servicios]    Script Date: 23/05/2023 23:11:22 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[servicios](
	[serv_id] [nchar](10) NULL,
	[serv_nom] [varchar](500) NULL,
	[serv_prec] [nchar](10) NULL
) ON [PRIMARY]
GO

# [dbo].[usuarios]

In [0]:
/****** Object:  Table [dbo].[usuarios]    Script Date: 23/05/2023 23:11:22 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[usuarios](
	[us_dni] [nvarchar](8) NULL,
	[us_cont] [nchar](100) NULL,
	[us_nom] [nchar](600) NULL,
	[us_direc] [nchar](400) NULL,
	[us_edad] [numeric](2, 0) NULL,
	[us_correo] [nchar](400) NULL,
	[us_Cel] [nchar](9) NOT NULL
) ON [PRIMARY]
GO

# [spa_forever]

In [0]:
USE [master]
GO

In [0]:
ALTER DATABASE [spa_forever] SET  READ_WRITE 
GO